apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::416886095162:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-2T72BGOK9LLU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::416886095162:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: '2020-05-20T13:09:37Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '886'
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d44333e5-e034-4b6f-8bf0-88829d35651f
